import uuid
import logging
from app.services.qwen_client import QwenClient
from app.services.oss_manager import OSSManager
from app.services.face_embedder import FaceEmbedder
from app.config import get_settings

logger = logging.getLogger(__name__)

# Fallback outfit when no wardrobe plan exists (never feed the face description in).
DEFAULT_OUTFIT = "a simple, well-fitted everyday outfit"

# Keep the reference identity, one person only, and no scene bleed-through.
CHAR_PLATE_NEGATIVE = (
    "two people, second person, multiple people, another person, crowd, background people, "
    "different person, different face, altered facial features, distorted face, deformed, "
    "full body, wide shot, room interior, doorway, scene, busy background, cluttered, text, watermark"
)


def subject_descriptor(gender: str | None = None, age: str | None = None,
                       appearance: str | None = None) -> str:
    """A concise 'who this is' phrase so plates stay CHARACTER-SPECIFIC even if the
    face-edit path can't run — otherwise two characters collapse into the same
    generic person. Uses gender/age/appearance, never the character's name (a name
    isn't visual)."""
    from app.services.voice_catalog import gender_bucket
    b = gender_bucket(gender)
    lead = "a woman" if b == "female" else "a man" if b == "male" else "a person"
    if age:
        lead = f"{lead} around {age}"
    appearance = (appearance or "").strip()
    if appearance:
        if len(appearance) > 220:  # keep the face from being drowned by a paragraph
            appearance = appearance[:220].rsplit(" ", 1)[0] + "…"
        return f"{lead}, {appearance}"
    return lead


def character_plate_prompt(has_face: bool, subject: str, outfit: str) -> str:
    """A costume-plate prompt tuned for FACE consistency AND a single subject: a
    waist-up studio shot (face stays large) of ONE person on a plain backdrop.
    `subject` describes who the character is (gender/age/appearance) so even the
    text-to-image fallback stays character-specific. outfit should be clothing only."""
    frame = ("Solo studio costume-reference photo of ONE person alone, no other people, "
             "waist-up medium portrait facing forward, plain seamless neutral backdrop, "
             "soft even lighting. Ignore any location, action or scene — plain background only.")
    if has_face:
        return (f"The exact same person as the reference image ({subject}) — keep the identical "
                f"face and hair, do not change the face. Wearing {outfit}. {frame}")
    return f"{subject}. Wearing {outfit}. {frame}"


class PlateGenerator:
    """Generates a reference plate (character costume, location, or style preset):
    Qwen image generation -> re-host on OSS -> (character only) ArcFace embedding.

    The generated image is downloaded ONCE; those bytes are both uploaded to OSS
    and (for character plates) fed to the face embedder — no second fetch.
    """

    def __init__(self, db=None):
        s = get_settings()
        self.qwen = QwenClient(s)
        self.oss = OSSManager(s)
        self.embedder = FaceEmbedder()
        self.db = db

    @staticmethod
    def _fetch_bytes(url: str) -> bytes:
        import httpx
        return httpx.get(url, timeout=60.0).content

    async def generate_and_store_plate(
        self, project_id: str, kind: str, key: str, prompt: str,
        style_ref: str | None = None, negative_prompt: str | None = None,
        base_image_url: str | None = None, prompt_extend: bool = True,
    ) -> tuple[str, list | None]:
        """kind in {character, location, style}. Returns (oss_url, face_vector|None).

        When base_image_url is set (a character's face reference), the costume plate
        is generated by image-editing that face so the identity is preserved. If the
        edit call fails, we fall back to plain text-to-image so a plate still lands
        (but the face will NOT match — the warning below flags that)."""
        if base_image_url:
            try:
                raw_url = await self.qwen.edit_image(
                    prompt, base_image_url, negative_prompt=negative_prompt, prompt_extend=prompt_extend)
            except Exception as e:  # noqa: BLE001 — degrade gracefully to text-to-image
                logger.warning(
                    "edit_image failed for %s/%s (%s) — falling back to text-to-image; "
                    "the face will NOT be preserved for this plate.", kind, key, e)
                raw_url = await self.qwen.generate_image(
                    prompt=prompt, negative_prompt=negative_prompt, prompt_extend=prompt_extend)
        else:
            raw_url = await self.qwen.generate_image(
                prompt=prompt, negative_prompt=negative_prompt, prompt_extend=prompt_extend)
        content = self._fetch_bytes(raw_url)
        # Unique filename per generation so a regenerated plate gets a NEW url — an
        # overwritten deterministic key returns the same url and the browser would
        # keep showing the cached (old) image.
        fname = f"{key.replace(':', '_')}_{uuid.uuid4().hex[:8]}.png"
        oss_key = self.oss.get_project_path(project_id, f"plates/{kind}", fname)
        oss_url = self.oss.upload_bytes(content, oss_key, content_type="image/png")

        if getattr(self, "db", None) is not None:
            from app.services.cost_ledger import record_image
            record_image(self.db, project_id, 1, stage="casting")

        vector = None
        if kind == "character":
            result = await self.embedder.extract(image_bytes=content, image_url=oss_url)
            vector = result.get("vector")

        return oss_url, vector
