import uuid
import logging
from app.services.qwen_client import QwenClient
from app.services.oss_manager import OSSManager
from app.services.face_embedder import FaceEmbedder
from app.config import get_settings

logger = logging.getLogger(__name__)

# Push the model to keep the reference identity and not wander into a scene.
CHAR_PLATE_NEGATIVE = (
    "different person, different face, altered facial features, distorted face, "
    "deformed, extra people, full body, wide shot, busy background, cluttered scene, text, watermark"
)


def character_plate_prompt(has_face: bool, visual_description: str | None,
                           name: str, outfit: str) -> str:
    """A costume-plate prompt tuned for FACE consistency: a waist-up shot (keeps the
    face large enough to survive) on a plain background. When a reference face exists
    the model is told to reuse that exact identity."""
    if has_face:
        return (f"The exact same person with the identical face, hairstyle and features as the "
                f"reference image — do not change the face. Waist-up medium portrait, facing "
                f"forward, wearing {outfit}. Plain neutral studio background, soft even lighting.")
    return (f"{visual_description or name}, waist-up medium portrait, facing forward, "
            f"wearing {outfit}. Plain neutral studio background, soft even lighting.")


class PlateGenerator:
    """Generates a reference plate (character costume, location, or style preset):
    Qwen image generation -> re-host on OSS -> (character only) ArcFace embedding.

    The generated image is downloaded ONCE; those bytes are both uploaded to OSS
    and (for character plates) fed to the face embedder — no second fetch.
    """

    def __init__(self, db=None):
        s = get_settings()
        self.qwen = QwenClient(s)
        self.oss = OSSManager(s)
        self.embedder = FaceEmbedder()
        self.db = db

    @staticmethod
    def _fetch_bytes(url: str) -> bytes:
        import httpx
        return httpx.get(url, timeout=60.0).content

    async def generate_and_store_plate(
        self, project_id: str, kind: str, key: str, prompt: str,
        style_ref: str | None = None, negative_prompt: str | None = None,
        base_image_url: str | None = None, prompt_extend: bool = True,
    ) -> tuple[str, list | None]:
        """kind in {character, location, style}. Returns (oss_url, face_vector|None).

        When base_image_url is set (a character's face reference), the costume plate
        is generated by image-editing that face so the identity is preserved. If the
        edit call fails, we fall back to plain text-to-image so a plate still lands
        (but the face will NOT match — the warning below flags that)."""
        if base_image_url:
            try:
                raw_url = await self.qwen.edit_image(
                    prompt, base_image_url, negative_prompt=negative_prompt, prompt_extend=prompt_extend)
            except Exception as e:  # noqa: BLE001 — degrade gracefully to text-to-image
                logger.warning(
                    "edit_image failed for %s/%s (%s) — falling back to text-to-image; "
                    "the face will NOT be preserved for this plate.", kind, key, e)
                raw_url = await self.qwen.generate_image(
                    prompt=prompt, negative_prompt=negative_prompt, prompt_extend=prompt_extend)
        else:
            raw_url = await self.qwen.generate_image(
                prompt=prompt, negative_prompt=negative_prompt, prompt_extend=prompt_extend)
        content = self._fetch_bytes(raw_url)
        # Unique filename per generation so a regenerated plate gets a NEW url — an
        # overwritten deterministic key returns the same url and the browser would
        # keep showing the cached (old) image.
        fname = f"{key.replace(':', '_')}_{uuid.uuid4().hex[:8]}.png"
        oss_key = self.oss.get_project_path(project_id, f"plates/{kind}", fname)
        oss_url = self.oss.upload_bytes(content, oss_key, content_type="image/png")

        if getattr(self, "db", None) is not None:
            from app.services.cost_ledger import record_image
            record_image(self.db, project_id, 1, stage="casting")

        vector = None
        if kind == "character":
            result = await self.embedder.extract(image_bytes=content, image_url=oss_url)
            vector = result.get("vector")

        return oss_url, vector
