"""audio_subsystem

Revision ID: 14b121ab861e
Revises: bc00464eed76
Create Date: 2026-07-02 11:19:45.482219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14b121ab861e'
down_revision: Union[str, Sequence[str], None] = 'bc00464eed76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_audio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('line_index', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('voice_id', sa.String(length=255), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('characters', sa.Column('voice_id', sa.String(length=255), nullable=True))
    op.add_column('characters', sa.Column('voice_model', sa.String(length=100), nullable=True))
    op.add_column('characters', sa.Column('voice_source', sa.String(length=20), nullable=True))
    op.add_column('characters', sa.Column('voice_sample_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'voice_sample_url')
    op.drop_column('characters', 'voice_source')
    op.drop_column('characters', 'voice_model')
    op.drop_column('characters', 'voice_id')
    op.drop_table('line_audio')
    # ### end Alembic commands ###
