"""production_bible

Revision ID: bc00464eed76
Revises: 003
Create Date: 2026-07-02 09:58:22.411774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'bc00464eed76'
down_revision: Union[str, Sequence[str], None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_plates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('location_key', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plate_image_url', sa.String(length=500), nullable=True),
    sa.Column('scene_numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('style_presets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('style_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('free_text', sa.Text(), nullable=True),
    sa.Column('plate_image_url', sa.String(length=500), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('costume_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('outfit_description', sa.Text(), nullable=True),
    sa.Column('plate_image_url', sa.String(length=500), nullable=True),
    sa.Column('face_vector', Vector(512), nullable=True),
    sa.Column('scene_numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('plate_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('characters', sa.Column('plate_status', sa.String(length=20), nullable=True))
    op.add_column('generated_clips', sa.Column('face_score', sa.Float(), nullable=True))
    op.add_column('generated_clips', sa.Column('outfit_score', sa.Float(), nullable=True))
    op.add_column('generated_clips', sa.Column('background_score', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('auto_approve_casting', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'auto_approve_casting')
    op.drop_column('generated_clips', 'background_score')
    op.drop_column('generated_clips', 'outfit_score')
    op.drop_column('generated_clips', 'face_score')
    op.drop_column('characters', 'plate_status')
    op.drop_table('costume_variants')
    op.drop_table('style_presets')
    op.drop_table('location_plates')
    # ### end Alembic commands ###
