"""agent_reports

Revision ID: ef68aed99bb8
Revises: 0e4d33376f39
Create Date: 2026-07-02 16:47:38.409737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef68aed99bb8'
down_revision: Union[str, Sequence[str], None] = '0e4d33376f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agent', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=True),
    sa.Column('decision', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_reports_project_id'), 'agent_reports', ['project_id'], unique=False)
    op.add_column('projects', sa.Column('auto_clarify', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'auto_clarify')
    op.drop_index(op.f('ix_agent_reports_project_id'), table_name='agent_reports')
    op.drop_table('agent_reports')
    # ### end Alembic commands ###
