"use client";

import { useEffect, useRef, useState } from "react";

// The five strongest EMBERWAKE shots: establish → mystery → horror → monster → payoff.
const HERO_CLIPS = [
  "/clip1.mp4",
  "/clip5.mp4",
  "/clip7.mp4",
  "/clip9.mp4",
  "/clip12.mp4",
];

const FADE_MS = 450;

export function HeroVideo() {
  const ref = useRef<HTMLVideoElement>(null);
  const [index, setIndex] = useState(0);
  const [visible, setVisible] = useState(true);

  // Load + play whenever the clip changes.
  useEffect(() => {
    const v = ref.current;
    if (!v) return;
    v.load();
    v.play().catch(() => {
      /* autoplay can be blocked until interaction; muted should allow it */
    });
  }, [index]);

  // Dissolve out, swap to the next clip, dissolve back in.
  const handleEnded = () => {
    setVisible(false);
    window.setTimeout(() => {
      setIndex((i) => (i + 1) % HERO_CLIPS.length);
      setVisible(true);
    }, FADE_MS);
  };

  return (
    <div className="relative w-full">
      {/* ambient violet glow behind the frame */}
      <div className="pointer-events-none absolute -inset-6 -z-10 rounded-[2rem] bg-primary/20 blur-3xl" />

      <div className="relative aspect-video w-full overflow-hidden rounded-2xl border hairline bg-black shadow-[0_0_90px_-20px_hsl(var(--primary)/0.6)]">
        <video
          ref={ref}
          muted
          playsInline
          autoPlay
          onEnded={handleEnded}
          className={`h-full w-full object-cover transition-opacity duration-500 ${
            visible ? "opacity-100" : "opacity-0"
          }`}
        >
          <source src={HERO_CLIPS[index]} type="video/mp4" />
        </video>

        {/* bottom gradient + caption */}
        <div className="pointer-events-none absolute inset-x-0 bottom-0 h-20 bg-gradient-to-t from-black/70 to-transparent" />
        <div className="absolute bottom-3 left-3 flex items-center gap-2">
          <span className="flex items-center gap-1.5 rounded-full bg-black/50 px-2.5 py-1 text-[11px] text-white/90 backdrop-blur-sm">
            <span className="h-1.5 w-1.5 rounded-full bg-bad animate-pulse" />
            EMBERWAKE · generated by Rexgent
          </span>
        </div>

        {/* progress dots */}
        <div className="absolute bottom-3 right-3 flex gap-1">
          {HERO_CLIPS.map((_, i) => (
            <span
              key={i}
              className={`h-1.5 rounded-full transition-all ${
                i === index ? "w-4 bg-white" : "w-1.5 bg-white/40"
              }`}
            />
          ))}
        </div>
      </div>
    </div>
  );
}
